packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@types/node": ^22.12.0
  tailwindcss: ^3.4.15
  typescript: ^5.7.3
  zod: ^3.24.1

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.8
    "@types/react-dom": ^19.0.3
  react-query:
    "@tanstack/react-query": ^5.66.0
    "@tanstack/react-query-devtools": ^5.66.0
